name: Format

on: [push, pull_request]

jobs:
  python-format:
    name: 'Python'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install python libraries
      shell: bash
      run: |
        pip install black==23.* pylint==3.2.7 pytest==7.* -r tools/requirements.txt

    - name: Run pylint and black
      shell: bash
      run: |
        pylint tools --ignore=build,ncc
        black --check tools --exclude=ncc
